KOMLOG_USERNAME = 'username'
KOMLOG_KEYFILE = 'keyfile'
ENTRY_LOG = 'logging'
ENTRY_PACKAGE = 'package'
LOG_FILE = 'filename'
LOG_DIR = 'dirname'
LOG_LEVEL = 'level'
LOG_ROTATION = 'rotation'
LOG_MAX_BYTES = 'max_bytes'
LOG_BACKUP_COUNT = 'backup_count'
LOG_FORMAT = 'format'
PACKAGE_ENABLED = 'enabled'
PACKAGE_INSTALL = 'install'
PACKAGE_VENV = 'venv'

